@startuml
'https://plantuml.com/sequence-diagram

entity instrumento{
codigo
precio
stock
}

entity trabajador{
nombre
apellido
rut
}

entity cliente{
nombre
apellido
rut
}

trabajador "1" --> "1..*" instrumento : registra
trabajador "1" --> "1" cliente : vende
@enduml